//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoQuestrader
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockTarget
    {
        public string SymbolName { get; set; }
        public double TargetPercent { get; set; }
        public string CategoryName { get; set; }
        public bool ShouldBuy { get; set; }
        public bool ShouldSell { get; set; }
    
        public virtual Category Category { get; set; }
    }
}
